### ISSUE TITLE
控制台无异常，但是无法访问页面

### ISSUE THREAD

**Issue by junbaor** [Coding/WebIDE-Backend#5]
![QQ截图20160914212100.png](https://ooo.0o0.ooo/2016/09/14/57d94f335ad9d.png)

---
1.  Frontend 工程的 build 目录是有四个文件的
2. 在 Frontend Webjars 工程下 执行 `mvn install` 结果为 `BUILD SUCCESS`
3. 使用 `mvn clean spring-boot:run` 启动 Backend 时控制台如上图所示
4. 浏览器访问 `http://ali.junbaor.com:8080/` 只是出现一个状态码为200的空白页
5. 访问 `http://ali.junbaor.com:8080/test` 会出现下图

![QQ截图20160914212448.png](https://ooo.0o0.ooo/2016/09/14/57d94fc4c99ab.png)

---

**Comment by hackape** [comment]
@tanhe123 java 这套我不熟，最好你来看一下了。

**Comment by hackape** [comment]
@junbaor 我先试着答，先试试看 fix 一个东西是 backend `/src/main/resources/application.properties` 里头 ALLOWED_ORIGIN, 把你域名加上。

**Comment by vangie** [comment]
@junbaor 出现状态码为200的页面控制台有没有错误？

**Comment by tanhe123** [comment]
访问了一下 http://ali.junbaor.com:8080/user 返回正确结果，说明程序已经成功运行起来了
可以按照 @hackape 的方法添加 ALLOWED_ORIGIN

**Comment by junbaor** [comment]
1. @vangie 出现状态码为 200 页面时控制台是没有任何信息输出的。

2. @hackape 已经按所述做出调整，问题依旧。下图是 diff  记录

---
![QQ截图20160914225558.png](https://ooo.0o0.ooo/2016/09/14/57d96509421c6.png)

**Comment by tanhe123** [comment]
帮忙执行下面两句：

```
cd WebIDE-Workspace/frontend-webjars/target
jar tvf frontend-1.0.0.jar
```

然后把结果贴一下

**Comment by junbaor** [comment]
@tanhe123 

![QQ截图20160914232853.png](https://ooo.0o0.ooo/2016/09/14/57d96cc0753e9.png)

**Comment by tanhe123** [comment]
文件大小不对~
可能是前端 build 出现问题了，可以这样看下：

```
cd WebIDE-Workspace/frontend/build
cat index.html
```

**Comment by hackape** [comment]
我同时提供另外一种思路啊，换种部署方式看看，因为这项目前后端是分离的，可以这样

1. `backend/ide.sh run` 让后端跑起来，然后到前端里头 `app/config.js` 里头有个 baseURL 配置项指向后端地址（现在是 http://ali.junbaor.com:8080）
2. cd 到 `frontend` 然后运行 `npm start` 会默认在 8060 起一个 `webpack-dev-server` 开发服务器，或者 `npm run build` 等待编译成静态 `build` 目录，然后自己 serve 这个目录，这样你 debug 下 `build` 目录下的静态文件，总能定位问题了

**Comment by junbaor** [comment]
@tanhe123  果然有问题, index.html 文件是空白的
@hackape 我慢慢消化一下  :smile:

**Comment by tanhe123** [comment]
重新 build 前端即可~

**Comment by hackape** [comment]
1. cd `frontend`
2. `npm run build`
3. 检查下编译完的 `build` 目录是不是正常

先确定这3点吧。

**Comment by junbaor** [comment]
执行 `npm run build` 就会卡死在这里, 再起个终端 ssh 就会被拒绝。
明天在本地搞个环境试试，感谢各位深夜指导 :+1: 


![QQ截图20160914235701.png](https://ooo.0o0.ooo/2016/09/14/57d9735e1f6da.png)

**Comment by junbaor** [comment]
抽空在本地起了个虚拟机，前端还是有点问题


### `npm run build `前端项目结果如下：

---

```
root@junbaor-virtual:~/coding/WebIDE/frontend# npm run build

> coding-web-ide@1.0.0 build /root/coding/WebIDE/frontend
> NODE_ENV=production ./node_modules/webpack/bin/webpack.js

Hash: d0f5027b790cd3395084
Version: webpack 1.13.2
Time: 75255ms
      Asset       Size  Chunks             Chunk Names
    main.js    1.23 MB       0  [emitted]  main
     1.1.js    4.48 MB       1  [emitted]  
 index.html  753 bytes          [emitted]  
favicon.ico    4.29 kB          [emitted]  
    + 610 hidden modules

ERROR in Cannot find module 'node-sass'
 @ ./app/styles/main.scss 4:14-141
Child html-webpack-plugin for "index.html":
        + 3 hidden modules
root@junbaor-virtual:~/coding/WebIDE/frontend# ll

```
### 相关版本信息如下：
```
node -v
v6.5.0

npm -v
3.10.3

python -V
Python 2.7.11+
```

### 访问首页源代码如下，但是依然是空白页面：
```
<!DOCTYPE html>
<html lang="zh-cn">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1,minimum-scale=1, maximum-scale=1">
  <title>Coding WebIDE 开启云端开发模式！ -  Coding.net</title>
  <meta name="Keywords" content="Coding.net,Coding,WebIDE,Web IDE,IDE,Git,代码托管,在线开发,在线调试,Terminal,开发环境分享,软件团队协作">
  <meta name="Description" content="Coding WebIDE 是Coding自主研发的在线集成开发环境。用户可以通过WebIDE创建项目的工作空间，进行在线开发，调试等操作。与此同时，WebIDE
    还提供了可分享的开发环境功能，用户可以保存当前的 Terminal 环境，分享给团队的其他成员。">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <script src="https://use.fontawesome.com/838df4727b.js"></script>
</head>
<body>
  <div id="root">
  </div>
<script type="text/javascript" src="main.js"></script></body>
</html>

```

**Comment by hackape** [comment]
你的 node-sass 没装上，再跑下 `npm install node-sass` 看看。

**Comment by junbaor** [comment]
@hackape  错误如下，google 好久搞不定 :flushed: 

```
root@junbaor-virtual:~/coding/WebIDE/frontend# npm install node-sass

> node-sass@3.10.0 install /root/coding/WebIDE/frontend/node_modules/node-sass
> node scripts/install.js

module.js:457
    throw err;
    ^

Error: Cannot find module '/root/coding/WebIDE/frontend/node_modules/node-sass/scripts/install.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN coding-web-ide@1.0.0 No repository field.
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/lib/nodejs/bin/node" "/lib/nodejs/bin/npm" "install" "node-sass"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.10.0 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.10.0 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/coding/WebIDE/frontend/npm-debug.log

```

**Comment by hackape** [comment]
https://github.com/sass/node-sass/issues/1484 看到说它对 node 6 不支持，我这边装的是 node v5.6.0 试试看？

**Comment by junbaor** [comment]
刚刚已经尝试着解决了，方式如下：

1.  全局安装  `npm install node-sass -g`
2.  `cp -r  /lib/nodejs/lib/node_modules/node-sass ~/coding/WebIDE/frontend/node_modules/`
3.  重新 build  前端工程 `npm run build`

> build 后文件大小如下：

```
root@junbaor-virtual:~/coding/WebIDE/frontend# npm run build

> coding-web-ide@1.0.0 build /root/coding/WebIDE/frontend
> NODE_ENV=production ./node_modules/webpack/bin/webpack.js

Hash: efa30b0a10ba9a7721e1
Version: webpack 1.13.2
Time: 75624ms
      Asset       Size  Chunks             Chunk Names
    main.js    1.38 MB       0  [emitted]  main
     1.1.js    4.48 MB       1  [emitted]  
 index.html  753 bytes          [emitted]  
favicon.ico    4.29 kB          [emitted]  
    + 611 hidden modules
Child html-webpack-plugin for "index.html":
        + 3 hidden modules
```

@hackape 所说的 node 版本问题待会我会重新搭建采用 node v5.6.0 试试

###  Thank you ! :+1:

**Comment by hackape** [comment]
@junbaor 你能帮我看看 /lib/nodejs/lib/node_modules/node-sass 的 package.json 里头它的版本号是多少吗？感觉除非是版本有差，不然这不科学啊，没道理全局装就好，local 装就不行的。

**Comment by junbaor** [comment]
@hackape v3.10.0

**Comment by hackape** [comment]
@node-sass 的 build 好像经常出平台相关的问题，我索性换成 stylus 了。
